sudo: false
dist: trusty

language: cpp
compiler:
  - clang

git:
  depth: 1

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:kzemek/boost'
    packages:
      - g++-6
      - libboost1.58-dev
      - libboost-filesystem1.58-dev
      - libboost-iostreams1.58-dev
      - libboost-program-options1.58-dev
      - libboost-regex1.58-dev
      - libboost-system1.58-dev
      - libboost-thread1.58-dev
      - libssl-dev
      - libmysqlclient-dev
      - libreadline6-dev
      - zlib1g-dev
      - libbz2-dev

services:
  - mysql

before_install:
  - git config user.email "travis@build.bot" && git config user.name "Travis CI"
  - git tag -a -m "Travis build" init

install:
  - mkdir bin
  - cd bin
  - cmake ../ -DWITH_WARNINGS=0 -DWITH_COREDEBUG=0 -DUSE_COREPCH=1 -DUSE_SCRIPTPCH=1 -DTOOLS=1 -DSCRIPTS=dynamic -DSERVERS=1 -DNOJEM=0 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_CXX_FLAGS_DEBUG="-DNDEBUG" -DCMAKE_INSTALL_PREFIX=check_install
  - cd ..

script:
  - $CXX --version
  - cd bin
  - make -j 4 -k && make install
  - cd check_install/bin
  - ./authserver --version
  - ./worldserver --version
